name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy code
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/ubuntu/quant-trading-nodejs
            git pull origin main
            npm install
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
          EOF
